### PR TITLE
add spanish

### PR DESCRIPTION
**Pull request by elespdn**
All the pipeline for Spanish is in a dedicated folder, because it has different requirements (compared to French).
The annoying part is that for NLP we use Freeling, which needs to be installed separately and the module for Old Spanish needs some fixed. Detailed installation instructions are in the README.

I've also changed some little things in pre-process and core, that could be applied to the French part as well (orderly, but not necessary):
- path indicated is the "main path", let's say, while it is specified inside the script that for --lemmatise it takes files inside 'txt' and for --collate the files inside 'xml'.
- the output of the collation goes inside the "main path" and not directly in the main dir

Evaluation is still missing, it's noted in the Issues for me.

### CODE REVIEW

**Comment by Jean-Baptiste-Camps** [comment]
Do you think we could try as well using the Pie model for Spanish, to see how it works ?

https://github.com/hipster-philology/pie-models/tree/master/es

**Comment by Jean-Baptiste-Camps** [comment]
Petit test: Entre muchas cosas estrañas que nuestro Señor Dios fizo, touo por bien de fazer una muy marauillosa; esta es que de quantos omnes en el mundo son non a uno que del todo paresca a otro en la cara.
````
token	lemma
Entre	entre
muchas	mucho
cosas	cosa
estrañas	estraña
que	que
nuestro	nuestro
Señor	señor
Dios	dios
fizo,	fizo,
touo	touo
por	por
bien	bien
de	de
fazer	fazer
una	uno
muy	mucho
marauillosa;	marauilloso
esta	este
es	ser
que	que
de	de
quantos	quanto
omnes	omnes
en	en
el	el
mundo	mundo
son	ser
non	non
a	a
uno	uno
que	que
del	del
todo	todo
paresca	paresca
a	a
otro	otro
en	en
la	el
cara.	cara
````


Entre muchas cosas estranas et marabillosas que nuestro señor dios fizo touo por bien de fazer una muy marabillosa Esta es de quantos en el mundo son non a uno que semeje a otro en la cara .

````
token	lemma
Entre	entre
muchas	mucho
cosas	cosa
estranas	estrana
et	et
marabillosas	marabilloso
que	que
nuestro	nuestro
señor	señor
dios	dio
fizo	fizo
touo	touo
por	por
bien	bien
de	de
fazer	fazer
una	uno
muy	mucho
marabillosa	marabilloso
Esta	este
es	ser
de	de
quantos	quanto
en	en
el	el
mundo	mundo
son	ser
non	non
a	a
uno	uno
que	que
semeje	semejer
a	a
otro	otro
en	en
la	el
cara	cara
.	.
````

**Comment by Jean-Baptiste-Camps** [comment]
Alternatively, we could train one, but we would need annotated Old Spanish texts for that. Don't know if there are any out there we could use ?

**Comment by elespdn** [comment]
No annotated corpora for Old Spanish that I know, but I was talking with Helena Bermudez Sabel and she is intersted in collaborating for annotating some of the existing corpora ... But I don't think this is possible now, before Utrecht.

**Comment by elespdn** [comment]
The result is quite nice!
Some testing is needed to check the results

**Pull request closed without merging**
