### PR TITLE
Compare automatic result with ideal result

### PR DESCRIPTION
**Pull request by elespdn**
Workaround for xml comparison: put all //rdg into a list and apply edit distance to the lists

For example, one first strophe Alexis:
if compare manually = 33 % of readings (cells in the table) do not correspond --> 33% errors
if compare using this approach = 20 % of readings do not correponds --> 20% errors

### CODE REVIEW

**Comment by elespdn** [comment]
Still have to add requirements

**Comment by elespdn** [comment]
This answers issue #15

**Comment by Jean-Baptiste-Camps** [comment]
Made some modifications to integrate into the core of the package, and provide an `eval.py` for direct use.

**Comment by Jean-Baptiste-Camps** [comment]
Some other modifications to be able to print diff or not, and to account for `app` boundaries.

**Pull request merged**
