### PR TITLE
Abstract lemm

### PR DESCRIPTION
**Pull request by elespdn**
This answer issue #12

MAIN calls LEMMATISE, which calls LEMMATISE_PIE or LEMMATISE_FREELING_SPO.

Requirements for old Spanish are separated, because they are quite different.

Everything should be documented in README.

**"Formal" changes**:
- rename dir 'collazione' > 'lemm_coll'
- rename 'core' > 'collation'
- delete 'preproc' and only have 'input' (see issue #18 )
-  'txt' > 'sources', because it includes txt and xml

**Please note**:
- LEMMATISE_PIE is modular, because it takes as arguments the path and the language. With Freeling cannot do the same, because the language is not enough, there are plenty of different paths to define together with it at least for old Spanish (because it is not complete and sometimes need to use parts of the modern Spanish one). I think it is OK for now, it is just less elegant for Freeling.

**To do**:
- add another language for pie, to showcase potentiality?? comments added in #12

### CODE REVIEW

**Comment by elespdn** [comment]
I forgot to add folder 'sources' into Alexis

**Comment by Jean-Baptiste-Camps** [comment]
All the new code seems great ! But, on a side note, why rename dir 'collazione' to 'lemm_coll' and  'core'  to 'collation' ?

**Comment by elespdn** [comment]
Mmm, only because in that directory there is code for the collation and for the lemmatisation and because I'm not sure which is the core of this pipeline, not sure there is one. BUT I absolutely do not mind other names and the old ones!
I think our concern should be on the transparency of the dir names (while on the repo I agree that something different can be the best!)

**Comment by Jean-Baptiste-Camps** [comment]
@elespdn Ok, thanks ! I'll look into this branch and set things up for merge. I'll make a proposition regarding names, but, in my opinion, the 'collazione' folder (name can be changed) contains our app / package in the Python sense, and all code should go in it (with possible subfolders), in the spirit of
https://docs.python.org/3.7/tutorial/modules.html#packages

**Comment by Jean-Baptiste-Camps** [comment]
Ok, now the workflow is broken with Pie, for an unknown reason, I'll try to restablish it (I think we need unit testing).

**Comment by Jean-Baptiste-Camps** [comment]
Just a path issue, it seems.

**Pull request merged**
